### ISSUE TITLE
Feature: add a  activate email-method to reduce Zombie email

### ISSUE THREAD

**Issue by AllianceTing** [openimsdk/openkf#34]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [OpenIMSDK Slack](https://join.slack.com/t/openimsdk/shared_invite/zt-1tmoj26uf-_FDy3dowVHBiGvLk9e5Xkg) and got positive feedback

### Is this feature request related to a problem?

❎ No

### Problem Description

as we all know , to use email-method-login open-im-kf may hava an bad influence on db-table,which may generate more zombie email account

### Solution Description

use activate email procedure to vertify email authenticity and correctness

### Benefits

reduce zombie account

### Potential Drawbacks

none

### Additional Information

none

**Comment by IRONICBo** [comment]
Sounds good, we have function that email-login should receive code and use code to register or create new account, see [SendCode](https://github.com/OpenIMSDK/OpenKF/blob/10f943bbb26125273f3db740424412598eb29ea2/server/internal/service/mail.go#L25)

**Comment by AllianceTing** [comment]
i hava a similar way 
use random key-stamp(email ,time-limited timestamp ...) to generate a new url and then to make user's email account activate

**Comment by AllianceTing** [comment]
please move it to next version
